module.exports.descriptors = [
    'Central',
    'Prime',
    'Golden',
    'Highway',
    'Express',
    'Greenfield',
    'Skyline',
    'Steel',
    'Dynamic',
    'Industrial',
    'Secure',
    'Eco',
    'Gateway',
    'Metro',
    'Alpha',
    'Capital',
    'Hub',
    'Ultra',
    'Rapid',
    'Blue',
    'Silver',
    'Steelcore',
    'Velocity',
    'Power'
];

module.exports.places = [
    'Depot',
    'Hub',
    'Storage Center',
    'Distribution Point',
    'Transit Center',
    'Warehouse',
    'Logistics Park',
    'Terminal',
    'Depot Bay',
    'Vault',
    'Facility',
    'Dock',
    'Hangar',
    'Container Yard',
    'Stack Yard',
    'Stockhouse',
    'Processing Center',
    'Bulk Storage',
    'Transit Hub',
    'Goods Terminal',
    'Staging Area',
    'Fulfillment Center',
    'Industrial Park',
    'Inventory Point',
    'Storage Yard'
];
