const mongoose = require('mongoose');
const Product = require('../models/product'); // Adjust the path as needed
const User = require('../models/user'); // Make sure to import the User model

// Database connection
mongoose.connect('mongodb://localhost:27017/hackathon', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const db = mongoose.connection;
db.on("error", console.error.bind(console, "connection error:"));
db.once("open", () => {
  console.log("Database connected");
});

// Function to seed products
const seedProducts = async () => {
  try {
    // Delete all existing products
    await Product.deleteMany({});
    console.log("All existing products deleted from the database.");

    // Fetch the first user from the database
    const user = await User.findOne();
    if (!user) {
      console.error("No user found. Please create a user in the database first.");
      return;
    }

const products = [
  {
    name: "Organic Rice",
    description: "High-quality organic rice, grown without chemicals.",
    price: 100,
    stock: 100,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRerdI-H7jEBcPAh3oJk_W03OOmJhGQh-6hYA&s",
    availability: true,
    type: "Cereal",
    category: "Grains",
    userId: user._id,
  },
  {
    name: "Fresh Tomatoes",
    description: "Ripe and juicy tomatoes perfect for your kitchen.",
    price: 50,
    stock: 200,
    image: "https://images.unsplash.com/photo-1582284540020-8acbe03f4924?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Wheat Flour",
    description: "Freshly milled wheat flour for all your baking needs.",
    price: 90,
    stock: 50,
    image: "https://images.unsplash.com/photo-1627735483792-233bf632619b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2hlYXQlMjBmbG91cnxlbnwwfHwwfHx8MA%3D%3D",
    availability: true,
    type: "Grain",
    category: "Grains",
    userId: user._id,
  },
  {
    name: "Tomato Seeds",
    description: "High-germination tomato seeds for your garden.",
    price: 25,
    stock: 500,
    image: "https://media.istockphoto.com/id/2157987208/photo/close-up-of-dried-organic-tomato-seeds-isolated-on-a-white-background-top-view.jpg",
    availability: true,
    type: "Seeds",
    category: "Seeds",
    userId: user._id,
  },
  {
    name: "Carrot",
    description: "Freshly harvested carrots, perfect for salads.",
    price: 40,
    stock: 150,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Apple",
    description: "Sweet and crisp apples straight from the orchard.",
    price: 70,
    stock: 120,
    image: "https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXBwbGV8ZW58MHx8MHx8fDA%3D",
    availability: true,
    type: "Fruit",
    category: "Fruits",
    userId: user._id,
  },
  {
    name: "Corn Seeds",
    description: "Premium corn seeds for high yield.",
    price: 30,
    stock: 300,
    image: "https://plus.unsplash.com/premium_photo-1667532212820-8f37c7f7ae72?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y29ybiUyMHNlZWRzfGVufDB8fDB8fHww",
    availability: true,
    type: "Seeds",
    category: "Seeds",
    userId: user._id,
  },
  {
    name: "Fertilizer Mix",
    description: "Organic fertilizer to boost your crop growth.",
    price: 80,
    stock: 75,
    image: "https://images.unsplash.com/photo-1661168929701-ea898de2dabd?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    availability: true,
    type: "Soil Nutrition",
    category: "Crop Nutrition",
    userId: user._id,
  },
  {
    name: "Green Beans",
    description: "Crisp and fresh green beans, straight from the farm.",
    price: 60,
    stock: 140,
    image: "https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JlZW4lMjBiZWFuc3xlbnwwfHwwfHx8MA%3D%3D",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Watermelon",
    description: "Juicy watermelon to refresh your day.",
    price: 90,
    stock: 90,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    availability: true,
    type: "Fruit",
    category: "Fruits",
    userId: user._id,
  },
  {
    name: "Paddy Seeds",
    description: "Top-grade paddy seeds for better crop productivity.",
    price: 35,
    stock: 450,
    image: "https://images.unsplash.com/photo-1651981350249-6173caeeb660?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cGFkZHl8ZW58MHx8MHx8fDA%3D",
    availability: true,
    type: "Seeds",
    category: "Seeds",
    userId: user._id,
  },
  {
    name: "Tractor Blade",
    description: "Heavy-duty tractor blade for ploughing.",
    price: 100,
    stock: 10,
    image: "https://media.istockphoto.com/id/2118541501/photo/disc-harrow-close-up.webp?a=1&b=1&s=612x612&w=0&k=20&c=znMqsXl66cslW4T25S1y1svAoEysKy703e55NnjwoAE=",
    availability: true,
    type: "Machinery",
    category: "Equipment",
    userId: user._id,
  },
  {
    name: "Potatoes",
    description: "Farm-fresh potatoes, great for all cooking needs.",
    price: 45,
    stock: 180,
    image: "https://images.unsplash.com/photo-1508313880080-c4bef0730395?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG90YXRvZXN8ZW58MHx8MHx8fDA%3D",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Urea Fertilizer",
    description: "Nitrogen-rich urea fertilizer for healthy growth.",
    price: 70,
    stock: 200,
    image: "https://media.istockphoto.com/id/1307738428/photo/sack-bag-and-granular-mineral-fertilizer-closeup.jpg?s=612x612&w=is&k=20&c=I5Qgut-rj_MvkoqNi_68DcMuSeUMyeYKjvy599Y3i90=",
    availability: true,
    type: "Crop Enhancer",
    category: "Crop Nutrition",
    userId: user._id,
  },
  {
    name: "Strawberry",
    description: "Delicious strawberries freshly picked.",
    price: 100,
    stock: 60,
    image: "https://images.unsplash.com/photo-1587393855524-087f83d95bc9?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c3RyYXdiZXJyeXxlbnwwfHwwfHx8MA%3D%3D",
    availability: true,
    type: "Fruit",
    category: "Fruits",
    userId: user._id,
  },
  {
    name: "Shovel",
    description: "Durable shovel for field work and gardening.",
    price: 95,
    stock: 25,
    image: "https://images.unsplash.com/photo-1596277922657-f80257171aec?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvdmVsfGVufDB8fDB8fHww",
    availability: true,
    type: "Tool",
    category: "Equipment",
    userId: user._id,
  },
  {
    name: "Onions",
    description: "Pungent and fresh onions straight from the soil.",
    price: 55,
    stock: 160,
    image: "https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Pumpkin",
    description: "Ripe pumpkins great for soups and pies.",
    price: 65,
    stock: 80,
    image: "https://images.unsplash.com/photo-1509622905150-fa66d3906e09?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cHVtcGtpbnxlbnwwfHwwfHx8MA%3D%3D",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Lettuce",
    description: "Leafy green lettuce for healthy salads.",
    price: 35,
    stock: 90,
    image: "https://images.unsplash.com/photo-1640958904159-51ae08bd3412?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGV0dHVjZXxlbnwwfHwwfHx8MA%3D%3D",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Cabbage",
    description: "Crunchy and fresh cabbage heads.",
    price: 30,
    stock: 110,
    image: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FiYmFnZXxlbnwwfHwwfHx8MA%3D%3D",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
   {
name: "Organic Bananas",
description: "Sweet organic bananas grown without pesticides.",
price: 30,
stock: 150,
image: "https://images.unsplash.com/photo-1744659753302-9f4fc320f085?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b3JnYW5pYyUyMGJhbm5hbmF8ZW58MHx8MHx8fDA%3D",
availability: true,
type: "Fruit",
category: "Fruits",
userId: user._id,
},
{
name: "Carrots",
description: "Crunchy and fresh carrots rich in beta-carotene.",
price: 40,
stock: 180,
image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2Fycm90fGVufDB8fDB8fHww",
availability: true,
type: "Vegetable",
category: "Vegetables",
userId: user._id,
},
{
name: "Organic Fertilizer",
description: "Nutrient-rich fertilizer for better crop yield.",
price: 90,
stock: 70,
image: "https://media.istockphoto.com/id/967945790/photo/organic-manure.jpg?s=612x612&w=is&k=20&c=L3Sny_7CmdnH7meBx8jAsS315jEXx2CrGY_aAy-3FX8=",
availability: true,
type: "Fertilizer",
category: "Crop Nutrition",
userId: user._id,
},
{
name: "Corn Seeds",
description: "High-quality hybrid corn seeds.",
price: 20,
stock: 300,
image: "https://images.unsplash.com/photo-1573804633927-8b1b2e5e92c0",
availability: true,
type: "Seeds",
category: "Seeds",
userId: user._id,
},
{
name: "Tractor",
description: "Heavy-duty tractor for plowing and hauling.",
price: 1000000,
stock: 5,
image: "https://unsplash.com/photos/green-and-yellow-tractor-in-garage-SPzzE4TYxZ0",
availability: true,
type: "Machinery",
category: "Equipment",
userId: user._id,
},
{
name: "Green Apples",
description: "Fresh and tangy green apples.",
price: 60,
stock: 100,
image: "https://images.unsplash.com/photo-1512578659172-63a4634c05ec?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JlZW4lMjBhcHBsZXN8ZW58MHx8MHx8fDA%3D",
availability: true,
type: "Fruit",
category: "Fruits",
userId: user._id,
},
{
name: "Lady Finger (Okra)",
description: "Tender and green lady finger for daily cooking.",
price: 45,
stock: 90,
image: "https://images.unsplash.com/photo-1664289242854-e99d345cfa92?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGFkeSUyMGZpbmdlcnxlbnwwfHwwfHx8MA%3D%3D",
availability: true,
type: "Vegetable",
category: "Vegetables",
userId: user._id,
},
{
name: "Potatoes",
description: "Freshly harvested potatoes perfect for all meals.",
price: 35,
stock: 200,
image: "https://images.unsplash.com/photo-1508313880080-c4bef0730395?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG90YXRvZXN8ZW58MHx8MHx8fDA%3D",
availability: true,
type: "Vegetable",
category: "Vegetables",
userId: user._id,
},
{
name: "Grapes",
description: "Juicy and sweet seedless grapes.",
price: 75,
stock: 80,
image: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Z3JhcGVzfGVufDB8fDB8fHww",
availability: true,
type: "Fruit",
category: "Fruits",
userId: user._id,
},
{
name: "Barley",
description: "Nutritious and organic barley grains.",
price: 85,
stock: 120,
image: "https://plus.unsplash.com/premium_photo-1705404738459-c4cb25ad7933?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFybGV5fGVufDB8fDB8fHww",
availability: true,
type: "Grain",
category: "Grains",
userId: user._id,
},
{
name: "Organic Pesticide",
description: "Eco-friendly pesticide to protect your crops.",
price: 60,
stock: 100,
image: "https://images.unsplash.com/photo-1550831107-1553da8c8464",
availability: true,
type: "Protection",
category: "Crop Nutrition",
userId: user._id,
},
{
name: "Watermelon Seeds",
description: "Grow juicy watermelons with our quality seeds.",
price: 25,
stock: 250,
image: "https://images.unsplash.com/photo-1615937659875-e7515cd665c3",
availability: true,
type: "Seeds",
category: "Seeds",
userId: user._id,
},
{
name: "Plough Machine",
description: "Durable plough for deep soil tilling.",
price: 100,
stock: 10,
image: "https://images.unsplash.com/photo-1615874959470-cb4799f96f80",
availability: true,
type: "Machinery",
category: "Equipment",
userId: user._id,
},
{
name: "Cauliflower",
description: "White and fresh cauliflower heads.",
price: 50,
stock: 110,
image: "https://images.unsplash.com/photo-1609132718482-73bc3024b2bb",
availability: true,
type: "Vegetable",
category: "Vegetables",
userId: user._id,
},
{
name: "Sugarcane",
description: "Juicy sugarcane sticks directly from the farm.",
price: 70,
stock: 90,
image: "https://images.unsplash.com/photo-1600096194375-c3ce1dc308cd",
availability: true,
type: "Crop",
category: "Grains",
userId: user._id,
},
{
name: "Neem Fertilizer",
description: "Natural neem-based fertilizer for soil health.",
price: 95,
stock: 60,
image: "https://images.unsplash.com/photo-1626371357984-2ec20c6784f1",
availability: true,
type: "Fertilizer",
category: "Crop Nutrition",
userId: user._id,
},
{
name: "Mangoes",
description: "Sweet and juicy seasonal mangoes.",
price: 100,
stock: 60,
image: "https://images.unsplash.com/photo-1590080876211-9f45c8d4e8e1",
availability: true,
type: "Fruit",
category: "Fruits",
userId: user._id,
},
{
name: "Peas",
description: "Fresh green peas for your cooking needs.",
price: 45,
stock: 95,
image: "https://images.unsplash.com/photo-1602518890150-3c2df28f2d62",
availability: true,
type: "Vegetable",
category: "Vegetables",
userId: user._id,
},
{
name: "Onions",
description: "Fresh onions directly from farm to kitchen.",
price: 40,
stock: 130,
image: "https://images.unsplash.com/photo-1617131701237-798c2a01c01b",
availability: true,
type: "Vegetable",
category: "Vegetables",
userId: user._id,
},
{
name: "Pumpkin Seeds",
description: "Healthy and edible pumpkin seeds.",
price: 30,
stock: 170,
image: "https://images.unsplash.com/photo-1628788092382-fbb3fefed9db",
availability: true,
type: "Seeds",
category: "Seeds",
userId: user._id,
},
{
  name: "Mango (Alphonso)",
  description: "Sweet and juicy Alphonso mangoes from Ratnagiri.",
  price: 180,
  stock: 60,
  image: "https://5.imimg.com/data5/SELLER/Default/2023/6/318282611/BZ/OG/GR/119768749/alphonso-mango-500x500.jpg",
  availability: true,
  type: "Fruit",
  category: "Fruits",
  userId: user._id,
},
{
  name: "Brinjal (Eggplant)",
  description: "Fresh brinjals, great for curries and fry dishes.",
  price: 40,
  stock: 100,
  image: "https://www.bigbasket.com/media/uploads/p/s/10000097_15-fresho-brinjal-bharta.jpg",
  availability: true,
  type: "Vegetable",
  category: "Vegetables",
  userId: user._id,
},
{
  name: "Tractor Plough",
  description: "Heavy-duty plough for deep soil tillage.",
  price: 95000,
  stock: 5,
  image: "https://5.imimg.com/data5/SELLER/Default/2022/12/SE/TT/UK/10609470/tractor-plough.jpg",
  availability: true,
  type: "Tool",
  category: "Equipment",
  userId: user._id,
},
{
  name: "Urea Fertilizer",
  description: "High nitrogen content fertilizer for crop growth.",
  price: 350,
  stock: 100,
  image: "https://agrikendra.com/image/cache/catalog/FERTILIZERS/Urea%20Fertilizer-750x750.jpg",
  availability: true,
  type: "Fertilizer",
  category: "Crop Nutrition",
  userId: user._id,
},
{
  name: "Carrot Seeds",
  description: "Premium quality carrot seeds with high yield potential.",
  price: 35,
  stock: 300,
  image: "https://www.greengoldseeds.co.in/wp-content/uploads/2021/10/Carrot.jpg",
  availability: true,
  type: "Seed",
  category: "Seeds",
  userId: user._id,
},
{
  name: "Barley",
  description: "Whole barley grains, excellent for health and livestock feed.",
  price: 60,
  stock: 200,
  image: "https://www.jiomart.com/images/product/original/491433256/barley-jau-grains-1-kg-product-images-o491433256-p491433256-0-202203171639.jpg",
  availability: true,
  type: "Grain",
  category: "Grains",
  userId: user._id,
},
{
  name: "Banana (Robusta)",
  description: "Fresh, ripe bananas rich in potassium.",
  price: 40,
  stock: 100,
  image: "https://media.post.rvohealth.io/wp-content/uploads/2020/09/bananas-bunch-732x549-thumbnail.jpg",
  availability: true,
  type: "Fruit",
  category: "Fruits",
  userId: user._id,
},
{
  name: "Cabbage",
  description: "Crisp and leafy green cabbage for salads and cooking.",
  price: 30,
  stock: 80,
  image: "https://5.imimg.com/data5/SELLER/Default/2023/1/JO/MZ/GF/155929756/cabbage-500x500.jpg",
  availability: true,
  type: "Vegetable",
  category: "Vegetables",
  userId: user._id,
},
{
  name: "Hand Sprayer",
  description: "Manual sprayer for applying fertilizers and pesticides.",
  price: 450,
  stock: 40,
  image: "https://m.media-amazon.com/images/I/61iqr07MSoL.AC_UF1000,1000_QL80.jpg",
  availability: true,
  type: "Tool",
  category: "Equipment",
  userId: user._id,
},
{
  name: "Neem Cake",
  description: "Organic manure and pest repellent for soil health.",
  price: 200,
  stock: 90,
  image: "https://5.imimg.com/data5/BX/MX/MY-4979744/neem-cake-500x500.jpg",
  availability: true,
  type: "Fertilizer",
  category: "Crop Nutrition",
  userId: user._id,
},
{
  name: "Maize Seeds",
  description: "Hybrid maize seeds with great germination rate.",
  price: 70,
  stock: 350,
  image: "https://www.agriplexindia.com/cdn/shop/products/maize_seed.png?v=1653562594",
  availability: true,
  type: "Seed",
  category: "Seeds",
  userId: user._id,
},
{
  name: "Ragi (Finger Millet)",
  description: "Nutrient-rich millet, good for baby and adult health.",
  price: 55,
  stock: 120,
  image: "https://5.imimg.com/data5/SELLER/Default/2022/5/NP/DK/UF/115876884/ragi-500x500.jpg",
  availability: true,
  type: "Grain",
  category: "Grains",
  userId: user._id,
},
{
  name: "Papaya",
  description: "Freshly harvested papaya rich in enzymes and fiber.",
  price: 60,
  stock: 75,
  image: "https://5.imimg.com/data5/ANDROID/Default/2023/7/328711693/WP/LR/WZ/19502197/product-jpeg-500x500.jpg",
  availability: true,
  type: "Fruit",
  category: "Fruits",
  userId: user._id,
},
{
  name: "Onions",
  description: "Essential kitchen vegetable, fresh and pungent.",
  price: 25,
  stock: 300,
  image: "https://5.imimg.com/data5/SELLER/Default/2023/2/WT/AK/CF/8278875/fresh-red-onion-500x500.jpg",
  availability: true,
  type: "Vegetable",
  category: "Vegetables",
  userId: user._id,
},
{
  name: "Electric Water Pump",
  description: "1HP submersible water pump for irrigation.",
  price: 5800,
  stock: 15,
  image: "https://m.media-amazon.com/images/I/61-1Nmh+UHL.AC_UF894,1000_QL80.jpg",
  availability: true,
  type: "Machine",
  category: "Equipment",
  userId: user._id,
},
  {
    name: "Cauliflower",
    description: "Snow-white cauliflower, fresh and pesticide-free.",
    price: 35,
    stock: 60,
    image: "https://5.imimg.com/data5/XA/AG/GLADMIN-59125589/cauliflower-500x500.png",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Guava",
    description: "Sweet and slightly tangy guavas packed with Vitamin C.",
    price: 45,
    stock: 80,
    image: "https://www.bigbasket.com/media/uploads/p/l/10000200_15-fresho-guava.jpg",
    availability: true,
    type: "Fruit",
    category: "Fruits",
    userId: user._id,
  },
  {
    name: "Green Gram (Moong Dal)",
    description: "Unpolished green gram, rich in protein and fiber.",
    price: 90,
    stock: 150,
    image: "https://www.jiomart.com/images/product/original/490004037/fortune-moong-dal-500-g-product-images-o490004037-p490004037-0-202203171732.jpg",
    availability: true,
    type: "Grain",
    category: "Grains",
    userId: user._id,
  },
  {
    name: "Lettuce Seeds",
    description: "Quick-growing lettuce seeds, ideal for kitchen gardening.",
    price: 30,
    stock: 400,
    image: "https://cdn.shopify.com/s/files/1/0574/8129/3846/products/ButterheadLettuce_1200x1200.jpg",
    availability: true,
    type: "Seed",
    category: "Seeds",
    userId: user._id,
  },
  {
    name: "Compost Fertilizer",
    description: "Organic compost made from natural decomposition.",
    price: 250,
    stock: 70,
    image: "https://5.imimg.com/data5/VF/CS/MY-41253749/organic-compost-fertilizer-500x500.jpg",
    availability: true,
    type: "Fertilizer",
    category: "Crop Nutrition",
    userId: user._id,
  },
  {
    name: "Battery Sprayer 16L",
    description: "Rechargeable battery sprayer for efficient spraying.",
    price: 2100,
    stock: 25,
    image: "https://5.imimg.com/data5/SELLER/Default/2021/7/CA/CI/KC/62477843/battery-sprayer-16l-500x500.jpg",
    availability: true,
    type: "Tool",
    category: "Equipment",
    userId: user._id,
  },
  {
    name: "Chilli Powder",
    description: "Pure red chilli powder made from premium dried chillies.",
    price: 95,
    stock: 120,
    image: "https://5.imimg.com/data5/SELLER/Default/2022/1/QE/JR/EV/11194331/chilli-powder-500x500.jpeg",
    availability: true,
    type: "Grain",
    category: "Grains",
    userId: user._id,
  },
  {
    name: "Lady Finger (Okra)",
    description: "Tender lady finger perfect for frying and curries.",
    price: 35,
    stock: 90,
    image: "https://www.bigbasket.com/media/uploads/p/l/10000144_15-fresho-ladies-finger.jpg",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Drumstick Seeds",
    description: "High-yield drumstick tree seeds with fast growth.",
    price: 50,
    stock: 300,
    image: "https://5.imimg.com/data5/KF/WJ/VL/SELLER-3091327/drumstick-seeds-500x500.jpg",
    availability: true,
    type: "Seed",
    category: "Seeds",
    userId: user._id,
  },
  {
    name: "Cow Manure",
    description: "Composted cow dung, excellent for soil enrichment.",
    price: 150,
    stock: 100,
    image: "https://5.imimg.com/data5/SELLER/Default/2022/7/WF/FR/AB/13441974/cow-manure-500x500.jpg",
    availability: true,
    type: "Fertilizer",
    category: "Crop Nutrition",
    userId: user._id,
  },
  {
    name: "Shovel (Heavy Duty)",
    description: "Metal farming shovel with ergonomic handle.",
    price: 650,
    stock: 40,
    image: "https://m.media-amazon.com/images/I/61Vxq7MIK8L.AC_UF894,1000_QL80.jpg",
    availability: true,
    type: "Tool",
    category: "Equipment",
    userId: user._id,
  },
  {
    name: "Spinach (Palak)",
    description: "Fresh green spinach rich in iron and vitamins.",
    price: 20,
    stock: 60,
    image: "https://www.bigbasket.com/media/uploads/p/l/40024666_9-fresho-spinach.jpg",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Pumpkin",
    description: "Orange pumpkins, great for curries and pies.",
    price: 30,
    stock: 50,
    image: "https://www.bigbasket.com/media/uploads/p/l/10000266_18-fresho-pumpkin-green-cut.jpg",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Peanuts (Groundnuts)",
    description: "High protein groundnuts, perfect for oil extraction.",
    price: 80,
    stock: 130,
    image: "https://5.imimg.com/data5/QX/QQ/MY-2/groundnut-seed-500x500.jpg",
    availability: true,
    type: "Grain",
    category: "Grains",
    userId: user._id,
  },
  {
    name: "Green Peas",
    description: "Fresh sweet peas, great for curries and snacks.",
    price: 60,
    stock: 80,
    image: "https://www.bigbasket.com/media/uploads/p/l/10000143_11-fresho-green-peas.jpg",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Organic Apple",
    description: "Crunchy apples grown organically in the hills.",
    price: 140,
    stock: 50,
    image: "https://5.imimg.com/data5/SELLER/Default/2023/1/FS/FC/XN/32592470/apple-500x500.jpg",
    availability: true,
    type: "Fruit",
    category: "Fruits",
    userId: user._id,
  },
  {
    name: "Tractor Trolley",
    description: "Heavy-duty tractor trolley for carrying harvest.",
    price: 45000,
    stock: 3,
    image: "https://5.imimg.com/data5/SELLER/Default/2021/4/QE/PL/KV/37961617/tractor-trolley-500x500.jpg",
    availability: true,
    type: "Machine",
    category: "Equipment",
    userId: user._id,
  },
  {
    name: "Potato",
    description: "Fresh and starchy potatoes straight from the farm.",
    price: 22,
    stock: 180,
    image: "https://www.bigbasket.com/media/uploads/p/l/10000159_15-fresho-potato.jpg",
    availability: true,
    type: "Vegetable",
    category: "Vegetables",
    userId: user._id,
  },
  {
    name: "Pomegranate",
    description: "Red, juicy pomegranates full of antioxidants.",
    price: 120,
    stock: 45,
    image: "https://5.imimg.com/data5/ANDROID/Default/2021/4/FX/FZ/UP/33850773/product-jpeg-500x500.jpg",
    availability: true,
    type: "Fruit",
    category: "Fruits",
    userId: user._id,
  },
  {
    name: "Coriander Seeds",
    description: "Flavor-rich coriander seeds for spice or sowing.",
    price: 55,
    stock: 160,
    image: "https://5.imimg.com/data5/SELLER/Default/2022/3/TV/FN/PL/4288236/coriander-seeds-500x500.jpg",
    availability: true,
    type: "Seed",
    category: "Seeds",
    userId: user._id,
  },
];

    // Insert sample products into the database
    await Product.insertMany(products);
    console.log("Sample products added to the database successfully!");
  } catch (error) {
    console.error("Error seeding products:", error);
  } finally {
    mongoose.connection.close(); // Close the connection after seeding
  }
};

// Call the seed function
seedProducts();
